### ISSUE TITLE
Set a FAT label

### ISSUE THREAD

**Issue by jkirk** [grml/grml2usb#32]
I think it would be nice to have a FAT label (automatically) assigned to the created USB device:
```
% sudo blkid /dev/sdb1 
/dev/sdb1: SEC_TYPE="msdos" UUID="D44E-9303" TYPE="vfat" PARTUUID="0005fd2d-01"

% sudo fatlabel /dev/sdb1 GRML 

% sudo blkid /dev/sdb1        
/dev/sdb1: SEC_TYPE="msdos" LABEL_FATBOOT="GRML" LABEL="GRML" UUID="D44E-9303" TYPE="vfat" PARTUUID="0005fd2d-01"
```

`GRML` as a label would be fine for me. Or anything else? Any objections?

**Comment by mika** [comment]
> GRML as a label would be fine for me. Or anything else? Any objections?

`GRML` sounds good to me!
